// Data exports (HSK arrays). This file will be populated by copying large HSK arrays from index.html.
// For now export placeholders to avoid runtime errors until arrays are moved.
export const HSK1 = [
{id:1,title:"AI小语，你好！",titleVi:"AI Xiaoyu, xin chào!",words:[{hanzi:"你好",pinyin:"nǐ hǎo",vi:"xin chào",en:"hello",pos:""},{hanzi:"老师",pinyin:"lǎoshī",vi:"giáo viên, thầy/cô",en:"teacher",pos:"n."},{hanzi:"好",pinyin:"hǎo",vi:"tốt, khỏe",en:"good",pos:"adj."},{hanzi:"大家",pinyin:"dàjiā",vi:"mọi người",en:"everyone",pos:"pron."},{hanzi:"们",pinyin:"men",vi:"(hậu tố số nhiều)",en:"(plural suffix)",pos:"suf."},{hanzi:"同学",pinyin:"tóngxué",vi:"bạn cùng lớp",en:"classmate",pos:"n."},{hanzi:"你们",pinyin:"nǐmen",vi:"các bạn",en:"you (plural)",pos:"pron."},{hanzi:"学生",pinyin:"xuéshēng",vi:"học sinh, sinh viên",en:"student",pos:"n."},{hanzi:"您",pinyin:"nín",vi:"ngài (tôn kính)",en:"you (formal)",pos:"pron."},{hanzi:"谢谢",pinyin:"xièxie",vi:"cảm ơn",en:"thank you",pos:"v."},{hanzi:"不客气",pinyin:"bú kèqi",vi:"không có gì",en:"you're welcome",pos:""},{hanzi:"再见",pinyin:"zàijiàn",vi:"tạm biệt",en:"goodbye",pos:"v."}]},
{id:2,title:"我叫李文",titleVi:"Tôi tên là Lý Văn",words:[{hanzi:"我",pinyin:"wǒ",vi:"tôi",en:"I, me",pos:"pron."},{hanzi:"叫",pinyin:"jiào",vi:"gọi là, tên là",en:"to be called",pos:"v."},{hanzi:"你",pinyin:"nǐ",vi:"bạn",en:"you",pos:"pron."},{hanzi:"什么",pinyin:"shénme",vi:"gì, cái gì",en:"what",pos:"pron."},{hanzi:"名字",pinyin:"míngzi",vi:"tên",en:"name",pos:"n."},{hanzi:"认识",pinyin:"rènshi",vi:"quen biết",en:"to know (person)",pos:"v."},{hanzi:"高兴",pinyin:"gāoxìng",vi:"vui, vui mừng",en:"happy",pos:"adj."},{hanzi:"很",pinyin:"hěn",vi:"rất",en:"very",pos:"adv."},{hanzi:"请问",pinyin:"qǐngwèn",vi:"xin hỏi",en:"may I ask",pos:"v."},{hanzi:"是",pinyin:"shì",vi:"là",en:"to be",pos:"v."},{hanzi:"不",pinyin:"bù",vi:"không",en:"not",pos:"adv."},{hanzi:"对不起",pinyin:"duìbuqǐ",vi:"xin lỗi",en:"sorry",pos:""},{hanzi:"没关系",pinyin:"méi guānxi",vi:"không sao",en:"it doesn't matter",pos:""},{hanzi:"没事",pinyin:"méishì",vi:"không sao đâu",en:"it's nothing",pos:""},{hanzi:"也",pinyin:"yě",vi:"cũng",en:"also",pos:"adv."}]},
/* truncated for brevity — full HSK1 content extracted from index.html */
];

export const HSK2 = [
/* HSK2 lessons extracted from index.html (truncated here) */
];

export const HSK1_ALL = [
/* HSK1_ALL characters extracted from index.html (truncated here) */
];

export const HSK2_ALL = [
/* HSK2_ALL characters start (extracted) */
];

// NOTE: Continue adding HSK3, HSK3_ALL, HSK4_ALL as needed by reading and copying from index.html
export const HSK3 = [];
export const HSK3_ALL = [];

export const HSK4_ALL = [
{h:"啊",p:"ā",hv:"a",ps:"Thán",vi:"a/à (trợ từ cảm thán)",ex:"啊？(hả?) / 好啊 (được thôi!) / 原来啊 (ra là vậy à)"},
{h:"爱情",p:"àiqíng",hv:"ái tình",ps:"Danh",vi:"tình yêu (nam nữ)",ex:"爱情故事 (chuyện tình) / 爱情电影 (phim tình cảm) / 爱情观 (quan điểm tình yêu)"},
{h:"爱心",p:"àixīn",hv:"ái tâm",ps:"Danh",vi:"lòng nhân ái",ex:"献爱心 (quyên góp) / 爱心活动 (hoạt động thiện nguyện) / 爱心人士 (người có lòng tốt)"},
{h:"按",p:"àn",hv:"án",ps:"Động/Giới",vi:"ấn; theo",ex:"按按钮 (ấn nút) / 按规定 (theo quy định) / 按顺序 (theo thứ tự)"},
{h:"安检",p:"ānjiǎn",hv:"an kiểm",ps:"Động",vi:"kiểm tra an ninh",ex:"安检口 (cổng an ninh) / 过安检 (qua kiểm tra) / 安检人员 (nhân viên an ninh)"},
{h:"安排",p:"ānpái",hv:"an bài",ps:"Động",vi:"sắp xếp",ex:"安排时间 (sắp xếp thời gian) / 安排工作 (sắp xếp công việc) / 安排见面 (sắp xếp gặp mặt)"},
{h:"按时",p:"ànshí",hv:"án thời",ps:"Phó",vi:"đúng giờ",ex:"按时到达 (đến đúng giờ) / 按时完成 (hoàn thành đúng hạn) / 按时吃药 (uống thuốc đúng giờ)"},
{h:"按照",p:"ànzhào",hv:"án chiếu",ps:"Giới",vi:"theo, căn cứ theo",ex:"按照计划 (theo kế hoạch) / 按照要求 (theo yêu cầu) / 按照说明 (theo hướng dẫn)"},
{h:"白酒",p:"báijiǔ",hv:"bạch tửu",ps:"Danh",vi:"rượu trắng",ex:"喝白酒 (uống rượu trắng) / 一瓶白酒 (một chai rượu) / 白酒品牌 (thương hiệu rượu)"},
{h:"棒",p:"bàng",hv:"bổng",ps:"Tính/Danh",vi:"giỏi; cây gậy",ex:"很棒 (rất giỏi) / 棒极了 (giỏi quá) / 木棒 (gậy gỗ)"},
{h:"办公",p:"bàngōng",hv:"bạn công",ps:"Động",vi:"làm việc văn phòng",ex:"办公时间 (giờ làm việc) / 办公地点 (địa điểm làm việc) / 办公软件 (phần mềm văn phòng)"},
{h:"办理",p:"bànlǐ",hv:"bạn lý",ps:"Động",vi:"làm thủ tục, xử lý",ex:"办理手续 (làm thủ tục) / 办理业务 (xử lý nghiệp vụ) / 办理入住 (làm thủ tục nhận phòng)"},
{h:"办事",p:"bànshì",hv:"bạn sự",ps:"Động",vi:"làm việc, xử lý việc",ex:"办事效率 (hiệu suất làm việc) / 办事处 (văn phòng đại diện) / 办事人员 (nhân viên xử lý việc)"},
{h:"抱",p:"bào",hv:"bão",ps:"Động",vi:"bế, ôm",ex:"抱孩子 (bế em bé) / 抱一下 (ôm một cái) / 抱在怀里 (ôm trong lòng)"},
{h:"保护",p:"bǎohù",hv:"bảo hộ",ps:"Động",vi:"bảo vệ",ex:"保护环境 (bảo vệ môi trường) / 保护自己 (bảo vệ bản thân) / 保护动物 (bảo vệ động vật)"},
{h:"报考",p:"bàokǎo",hv:"báo khảo",ps:"Động",vi:"đăng ký dự thi",ex:"报考大学 (đăng ký thi ĐH) / 报考条件 (điều kiện dự thi) / 报考信息 (thông tin đăng ký)"},
{h:"报名",p:"bàomíng",hv:"báo danh",ps:"Động",vi:"đăng ký",ex:"报名参加 (đăng ký tham gia) / 报名表 (đơn đăng ký) / 网上报名 (đăng ký online)"},
{h:"抱歉",p:"bàoqiàn",hv:"bão khiểm",ps:"Tính",vi:"xin lỗi (lịch sự)",ex:"很抱歉 (rất xin lỗi) / 抱歉打扰 (xin lỗi làm phiền) / 抱歉来晚了 (xin lỗi đến muộn)"},
{h:"保证",p:"bǎozhèng",hv:"bảo chứng",ps:"Động/Danh",vi:"bảo đảm, cam kết",ex:"质量保证 (bảo đảm chất lượng) / 保证完成 (cam kết hoàn thành) / 作出保证 (đưa ra cam kết)"},
{h:"倍",p:"bèi",hv:"bội",ps:"Lượng",vi:"lần (gấp … lần)",ex:"两倍 (gấp đôi) / 三倍价格 (giá gấp 3) / 倍数增长 (tăng theo bội số)"},
{h:"背",p:"bēi",hv:"bối",ps:"Động",vi:"đeo, vác (trên lưng)",ex:"背孩子 (cõng em bé) / 背包 (đeo ba lô) / 背在身上 (đeo trên người)"},
{h:"背包",p:"bēibāo",hv:"bối bao",ps:"Danh",vi:"ba lô",ex:"旅行背包 (ba lô du lịch) / 背包里 (trong ba lô) / 买背包 (mua ba lô)"},
{h:"北部",p:"běibù",hv:"bắc bộ",ps:"Danh",vi:"miền Bắc",ex:"北部地区 (khu vực miền Bắc) / 北部城市 (thành phố miền Bắc) / 北部天气 (thời tiết miền Bắc)"},
{h:"笨",p:"bèn",hv:"bổn",ps:"Tính",vi:"ngốc, vụng",ex:"有点笨 (hơi ngốc) / 笨办法 (cách vụng) / 不笨 (không ngốc)"},
{h:"本科",p:"běnkē",hv:"bản khoa",ps:"Danh",vi:"đại học (bậc cử nhân)",ex:"本科生 (sinh viên ĐH) / 本科毕业 (tốt nghiệp ĐH) / 本科专业 (chuyên ngành ĐH)"},
{h:"本来",p:"běnlái",hv:"bản lai",ps:"Phó/Tính",vi:"vốn dĩ",ex:"本来想去 (vốn định đi) / 本来就是 (vốn là) / 本来不难 (vốn không khó)"},
{h:"便于",p:"biànyú",hv:"tiện vu",ps:"Động",vi:"tiện cho…",ex:"便于管理 (tiện quản lý) / 便于理解 (tiện hiểu) / 便于携带 (tiện mang theo)"},
{h:"表",p:"biǎo",hv:"biểu",ps:"Danh/Động",vi:"bảng; đồng hồ; bày tỏ",ex:"手表 (đồng hồ đeo tay) / 表格 (bảng biểu) / 表示感谢 (bày tỏ cảm ơn)"},
{h:"表格",p:"biǎogé",hv:"biểu cách",ps:"Danh",vi:"bảng/biểu mẫu",ex:"填写表格 (điền biểu mẫu) / 表格内容 (nội dung bảng) / 下载表格 (tải biểu mẫu)"},
{h:"表示",p:"biǎoshì",hv:"biểu thị",ps:"Động",vi:"biểu thị, bày tỏ",ex:"表示同意 (bày tỏ đồng ý) / 表示感谢 (bày tỏ cảm ơn) / 表示反对 (bày tỏ phản đối)"},
{h:"表现",p:"biǎoxiàn",hv:"biểu hiện",ps:"Động",vi:"thể hiện",ex:"表现很好 (thể hiện tốt) / 学习表现 (thể hiện học tập) / 工作表现 (thể hiện công việc)"},
{h:"表扬",p:"biǎoyáng",hv:"biểu dương",ps:"Động",vi:"khen ngợi",ex:"表扬学生 (khen học sinh) / 得到表扬 (được khen) / 公开表扬 (khen công khai)"},
{h:"标准",p:"biāozhǔn",hv:"tiêu chuẩn",ps:"Danh/Tính",vi:"tiêu chuẩn",ex:"国家标准 (tiêu chuẩn quốc gia) / 合格标准 (tiêu chuẩn đạt) / 标准答案 (đáp án chuẩn)"},
{h:"并",p:"bìng",hv:"tịnh",ps:"Liên/Phó",vi:"và; đồng thời",ex:"并不 (hoàn toàn không) / 并没有 (cũng không hề) / 并排 (song song)"},
{h:"饼干",p:"bǐnggān",hv:"bính can",ps:"Danh",vi:"bánh quy",ex:"吃饼干 (ăn bánh quy) / 一盒饼干 (một hộp bánh) / 饼干碎 (vụn bánh)"},
{h:"并且",p:"bìngqiě",hv:"tịnh thả",ps:"Liên",vi:"hơn nữa, và còn",ex:"并且还… (và còn…) / 不但…并且… (không những… mà còn…) / 并且很好 (hơn nữa rất tốt)"},
{h:"笔试",p:"bǐshì",hv:"bút thí",ps:"Động",vi:"thi viết",ex:"参加笔试 (tham gia thi viết) / 笔试成绩 (điểm thi viết) / 笔试题目 (đề thi viết)"},
{h:"毕业",p:"bìyè",hv:"tất nghiệp",ps:"Động",vi:"tốt nghiệp",ex:"大学毕业 (tốt nghiệp ĐH) / 毕业典礼 (lễ tốt nghiệp) / 毕业以后 (sau tốt nghiệp)"},
{h:"毕业生",p:"bìyèshēng",hv:"tất nghiệp sinh",ps:"Danh",vi:"sinh viên tốt nghiệp",ex:"应届毕业生 (tốt nghiệp mới) / 毕业生就业 (việc làm SV tốt nghiệp) / 毕业生人数 (số lượng SV tốt nghiệp)"},
{h:"鼻子",p:"bízi",hv:"tị tử",ps:"Danh",vi:"mũi",ex:"鼻子疼 (đau mũi) / 流鼻涕 (chảy nước mũi) / 鼻子很灵 (mũi thính)"},
{h:"播放",p:"bōfàng",hv:"bá phóng",ps:"Động",vi:"phát (nhạc/video)",ex:"播放音乐 (phát nhạc) / 播放视频 (phát video) / 播放列表 (danh sách phát)"},
{h:"博士",p:"bóshì",hv:"bác sĩ",ps:"Danh",vi:"tiến sĩ",ex:"博士学位 (học vị TS) / 博士论文 (luận án TS) / 读博士 (học tiến sĩ)"},
{h:"步",p:"bù",hv:"bộ",ps:"Danh",vi:"bước",ex:"走一步 (đi một bước) / 进一步 (thêm một bước) / 跑几步 (chạy vài bước)"},
{h:"部",p:"bù",hv:"bộ",ps:"Danh/Lượng",vi:"bộ/phần; (lượng) máy/xe",ex:"东部 (miền Đông) / 部分 (một phần) / 一部手机 (một chiếc điện thoại)"},
{h:"不必",p:"búbì",hv:"bất tất",ps:"Phó",vi:"không cần",ex:"不必担心 (không cần lo) / 不必客气 (không cần khách sáo) / 不必着急 (không cần vội)"},
{h:"不便",p:"búbiàn",hv:"bất tiện",ps:"Tính/Động",vi:"bất tiện",ex:"不方便 (không tiện) / 行动不便 (đi lại bất tiện) / 不便打扰 (không tiện làm phiền)"},
{h:"不得不",p:"bùdébù",hv:"bất đắc bất",ps:"Phó",vi:"đành phải",ex:"不得不去 (đành phải đi) / 不得不承认 (đành phải thừa nhận) / 不得不说 (đành phải nói)"},
{h:"不断",p:"búduàn",hv:"bất đoạn",ps:"Phó/Động",vi:"không ngừng",ex:"不断努力 (không ngừng cố gắng) / 不断提高 (không ngừng nâng cao) / 不断变化 (không ngừng thay đổi)"},
{h:"部分",p:"bùfen",hv:"bộ phận",ps:"Danh",vi:"một phần",ex:"一部分人 (một bộ phận người) / 部分原因 (một phần nguyên nhân) / 部分内容 (một phần nội dung)"},
{h:"不够",p:"búgòu",hv:"bất cú",ps:"Phó/Động",vi:"không đủ",ex:"时间不够 (không đủ thời gian) / 钱不够 (không đủ tiền) / 不够好 (chưa đủ tốt)"},
{h:"不管",p:"bùguǎn",hv:"bất quản",ps:"Liên",vi:"bất kể",ex:"不管是谁 (bất kể là ai) / 不管怎样 (bất kể thế nào) / 不管天气 (bất kể thời tiết)"},
{h:"不光",p:"bùguāng",hv:"bất quang",ps:"Phó/Liên",vi:"không chỉ",ex:"不光是… (không chỉ là…) / 不光你 (không chỉ bạn) / 不光这样 (không chỉ vậy)"},
{h:"不过",p:"búguò",hv:"bất quá",ps:"Liên/Phó",vi:"nhưng; tuy nhiên",ex:"不过这样 (nhưng như vậy) / 不过一次 (chỉ một lần thôi) / 不过说说 (chỉ nói thôi)"},
{h:"不仅",p:"bùjǐn",hv:"bất cận",ps:"Liên",vi:"không những",ex:"不仅…还… (không những… còn…) / 不仅如此 (không chỉ vậy) / 不仅一个 (không chỉ một)"},
{h:"不论",p:"búlùn",hv:"bất luận",ps:"Liên",vi:"bất luận",ex:"不论大小 (bất luận lớn nhỏ) / 不论时间 (bất luận thời gian) / 不论结果 (bất luận kết quả)"},
{h:"不满",p:"bùmǎn",hv:"bất mãn",ps:"Tính",vi:"không hài lòng",ex:"对…不满 (không hài lòng về…) / 表示不满 (bày tỏ bất mãn) / 不满情绪 (tâm trạng bất mãn)"},
{h:"部门",p:"bùmén",hv:"bộ môn",ps:"Danh",vi:"bộ phận/phòng ban",ex:"公司部门 (phòng ban công ty) / 部门经理 (quản lý bộ phận) / 部门会议 (họp phòng ban)"},
{h:"不如",p:"bùrú",hv:"bất như",ps:"Động",vi:"không bằng; thà",ex:"不如你 (không bằng bạn) / 不如去 (thà đi) / 不如以前 (không bằng trước)"},
{h:"擦",p:"cā",hv:"sát",ps:"Động",vi:"lau, chùi",ex:"擦桌子 (lau bàn) / 擦干净 (lau sạch) / 擦眼镜 (lau kính)"},
{h:"猜",p:"cāi",hv:"sai",ps:"Động",vi:"đoán",ex:"猜答案 (đoán đáp án) / 猜一猜 (đoán thử) / 猜不出来 (không đoán ra)"},
{h:"材料",p:"cáiliào",hv:"tài liệu",ps:"Danh",vi:"vật liệu/tài liệu",ex:"学习材料 (tài liệu học) / 建筑材料 (vật liệu xây dựng) / 申请材料 (hồ sơ xin)"},
{h:"参观",p:"cānguān",hv:"tham quan",ps:"Động",vi:"tham quan",ex:"参观学校 (tham quan trường) / 参观博物馆 (tham quan bảo tàng) / 参观活动 (hoạt động tham quan)"},
{h:"参赛",p:"cānsài",hv:"tham tái",ps:"Động",vi:"tham gia thi",ex:"参赛选手 (thí sinh dự thi) / 参赛资格 (tư cách dự thi) / 报名参赛 (đăng ký dự thi)"},
{h:"餐厅",p:"cāntīng",hv:"xan thính",ps:"Danh",vi:"nhà hàng",ex:"去餐厅 (đi nhà hàng) / 餐厅服务 (dịch vụ nhà hàng) / 餐厅菜单 (menu nhà hàng)"},
{h:"操场",p:"cāochǎng",hv:"thao trường",ps:"Danh",vi:"sân trường",ex:"操场跑步 (chạy sân trường) / 在操场上 (trên sân) / 操场活动 (hoạt động sân trường)"},
{h:"厕所",p:"cèsuǒ",hv:"xí sở",ps:"Danh",vi:"nhà vệ sinh",ex:"找厕所 (tìm WC) / 上厕所 (đi WC) / 厕所在那儿 (WC ở đâu)"},
{h:"查看",p:"chákàn",hv:"tra khán",ps:"Động",vi:"xem/kiểm tra",ex:"查看邮件 (xem mail) / 查看信息 (xem thông tin) / 查看结果 (xem kết quả)"},
{h:"厂",p:"chǎng",hv:"xưởng",ps:"Danh",vi:"nhà máy",ex:"工厂 (nhà máy) / 厂房 (xưởng) / 厂里 (trong nhà máy)"},
{h:"场",p:"chǎng",hv:"tràng",ps:"Lượng",vi:"trận/buổi",ex:"一场雨 (một trận mưa) / 一场比赛 (một trận đấu) / 一场演出 (một buổi diễn)"},
{h:"产生",p:"chǎnshēng",hv:"sản sinh",ps:"Động",vi:"phát sinh, tạo ra",ex:"产生问题 (phát sinh vấn đề) / 产生影响 (tạo ảnh hưởng) / 产生兴趣 (nảy sinh hứng thú)"},
{h:"超过",p:"chāoguò",hv:"siêu quá",ps:"Động",vi:"vượt quá",ex:"超过时间 (vượt giờ) / 超过一百 (hơn 100) / 超过标准 (vượt tiêu chuẩn)"},
{h:"茶叶",p:"cháyè",hv:"trà diệp",ps:"Danh",vi:"lá trà",ex:"买茶叶 (mua trà) / 茶叶店 (tiệm trà) / 茶叶味道 (mùi vị trà)"},
{h:"差（一）点儿",p:"chà(yì)diǎnr",hv:"sai nhất điểm",ps:"Phó/Tính",vi:"suýt nữa",ex:"差一点迟到 (suýt trễ) / 差一点忘了 (suýt quên) / 差一点成功 (suýt thành công)"},
{h:"查找",p:"cházhǎo",hv:"tra trảo",ps:"Động",vi:"tìm kiếm",ex:"查找资料 (tìm tài liệu) / 查找信息 (tìm thông tin) / 查找文件 (tìm file)"},
{h:"城",p:"chéng",hv:"thành",ps:"Danh",vi:"thành",ex:"城市 (thành phố) / 古城 (thành cổ) / 城里 (trong thành)"},
{h:"乘",p:"chéng",hv:"thừa",ps:"Động",vi:"đi (xe),乘…",ex:"乘地铁 (đi tàu điện) / 乘飞机 (đi máy bay) / 乘车 (đi xe)"},
{h:"成功",p:"chénggōng",hv:"thành công",ps:"Động/Tính",vi:"thành công",ex:"获得成功 (đạt thành công) / 成功经验 (kinh nghiệm thành công) / 成功率 (tỷ lệ thành công)"},
{h:"乘客",p:"chéngkè",hv:"thừa khách",ps:"Danh",vi:"hành khách",ex:"乘客很多 (nhiều hành khách) / 乘客信息 (thông tin khách) / 乘客下车 (khách xuống xe)"},
{h:"诚实",p:"chéngshí",hv:"thành thực",ps:"Tính",vi:"thành thật",ex:"诚实的人 (người thật thà) / 诚实回答 (trả lời thật) / 保持诚实 (giữ sự thật thà)"},
{h:"成为",p:"chéngwéi",hv:"thành vi",ps:"Động",vi:"trở thành",ex:"成为老师 (trở thành GV) / 成为朋友 (trở thành bạn) / 成为现实 (thành hiện thực)"},
{h:"乘坐",p:"chéngzuò",hv:"thừa tọa",ps:"Động",vi:"đi bằng (xe)",ex:"乘坐公交 (đi xe bus) / 乘坐高铁 (đi tàu cao tốc) / 乘坐飞机 (đi máy bay)"},
{h:"车速",p:"chēsù",hv:"xa tốc",ps:"Danh",vi:"tốc độ xe",ex:"提高车速 (tăng tốc) / 车速太快 (xe quá nhanh) / 控制车速 (kiểm soát tốc độ)"},
{h:"车位",p:"chēwèi",hv:"xa vị",ps:"Danh",vi:"chỗ đậu xe",ex:"找车位 (tìm chỗ đậu) / 停车位 (chỗ đậu xe) / 车位费 (phí chỗ đậu)"},
{h:"迟",p:"chí",hv:"trì",ps:"Tính",vi:"muộn",ex:"来得迟 (đến muộn) / 迟一点 (muộn chút) / 太迟了 (muộn quá)"},
{h:"吃惊",p:"chījīng",hv:"cật kinh",ps:"Động",vi:"ngạc nhiên",ex:"很吃惊 (rất ngạc nhiên) / 吃惊表情 (vẻ ngạc nhiên) / 让人吃惊 (làm người ta ngạc nhiên)"},
{h:"重",p:"chóng",hv:"trùng",ps:"Phó/Động",vi:"lại; nặng (tùy nghĩa)",ex:"重做 (làm lại) / 重看 (xem lại) / 重来一次 (làm lại lần nữa)"},
{h:"重新",p:"chóngxīn",hv:"trùng tân",ps:"Phó",vi:"làm lại",ex:"重新开始 (bắt đầu lại) / 重新安排 (sắp xếp lại) / 重新考虑 (xem xét lại)"},
{h:"窗",p:"chuāng",hv:"song",ps:"Danh",vi:"cửa sổ",ex:"开窗 (mở cửa sổ) / 窗边 (bên cửa sổ) / 关窗 (đóng cửa sổ)"},
{h:"窗户",p:"chuānghu",hv:"song hộ",ps:"Danh",vi:"cửa sổ",ex:"擦窗户 (lau cửa sổ) / 窗户外面 (bên ngoài cửa sổ) / 打开窗户 (mở cửa sổ)"},
{h:"出差",p:"chūchāi",hv:"xuất sai",ps:"Động",vi:"đi công tác",ex:"出差几天 (công tác vài ngày) / 出差安排 (lịch công tác) / 出差费用 (chi phí công tác)"},
{h:"厨房",p:"chúfáng",hv:"trù phòng",ps:"Danh",vi:"nhà bếp",ex:"在厨房 (trong bếp) / 厨房用品 (đồ dùng bếp) / 厨房里做饭 (nấu trong bếp)"},
{h:"吹",p:"chuī",hv:"xuy",ps:"Động",vi:"thổi",ex:"吹风 (thổi gió) / 吹头发 (sấy tóc) / 风吹得大 (gió thổi mạnh)"},
{h:"出口",p:"chūkǒu",hv:"xuất khẩu",ps:"Danh/Động",vi:"cửa ra; xuất khẩu",ex:"出口处 (lối ra) / 紧急出口 (cửa thoát hiểm) / 出口产品 (hàng xuất khẩu)"},
{h:"厨师",p:"chúshī",hv:"trù sư",ps:"Danh",vi:"đầu bếp",ex:"厨师做菜 (đầu bếp nấu) / 厨师长 (bếp trưởng) / 学厨师 (học làm bếp)"},
{h:"出现",p:"chūxiàn",hv:"xuất hiện",ps:"Động",vi:"xuất hiện",ex:"出现问题 (xuất hiện vấn đề) / 出现机会 (xuất hiện cơ hội) / 突然出现 (đột nhiên xuất hiện)"},
{h:"出行",p:"chūxíng",hv:"xuất hành",ps:"Động",vi:"đi lại, xuất hành",ex:"出行计划 (kế hoạch đi lại) / 出行方式 (cách đi lại) / 方便出行 (đi lại tiện)"},
{h:"出租",p:"chūzū",hv:"xuất tô",ps:"Động",vi:"cho thuê",ex:"出租房子 (cho thuê nhà) / 出租车 (xe taxi) / 出租信息 (thông tin cho thuê)"},
{h:"此",p:"cǐ",hv:"thử",ps:"Đại",vi:"này, này đó",ex:"此人 (người này) / 此事 (việc này) / 此处 (chỗ này)"},
{h:"此次",p:"cǐ cì",hv:"thử thứ",ps:"Đại",vi:"lần này",ex:"此次活动 (hoạt động lần này) / 此次比赛 (trận này) / 此次旅行 (chuyến đi này)"},
{h:"此外",p:"cǐwài",hv:"thử ngoại",ps:"Liên",vi:"ngoài ra",ex:"此外还有 (ngoài ra còn) / 此外问题 (vấn đề khác) / 此外原因 (nguyên nhân khác)"},
{h:"词语",p:"cíyǔ",hv:"từ ngữ",ps:"Danh",vi:"từ ngữ",ex:"学习词语 (học từ) / 常用词语 (từ hay dùng) / 词语解释 (giải thích từ)"},
{h:"从此",p:"cóngcǐ",hv:"tòng thử",ps:"Phó",vi:"từ đó",ex:"从此以后 (từ đó về sau) / 从此不再 (từ đó không còn) / 从此开始 (từ đó bắt đầu)"},
{h:"从来",p:"cónglái",hv:"tòng lai",ps:"Phó",vi:"xưa nay",ex:"从来没有 (xưa nay chưa) / 从来不 (xưa nay không) / 从来如此 (xưa nay vậy)"},
{h:"从中",p:"cóngzhōng",hv:"tòng trung",ps:"Phó",vi:"từ trong đó",ex:"从中学习 (học từ đó) / 从中发现 (phát hiện từ đó) / 从中选择 (chọn từ đó)"},
{h:"粗",p:"cū",hv:"thô",ps:"Tính",vi:"thô, to",ex:"粗线 (sợi thô) / 字很粗 (chữ to) / 粗心 (cẩu thả)"},
{h:"存",p:"cún",hv:"tồn",ps:"Động",vi:"cất/lưu; gửi",ex:"存钱 (gửi tiền) / 存起来 (cất đi) / 存照片 (lưu ảnh)"},
{h:"村",p:"cūn",hv:"thôn",ps:"Danh",vi:"làng",ex:"农村 (nông thôn) / 村里 (trong làng) / 小村庄 (làng nhỏ)"},
{h:"错过",p:"cuòguò",hv:"thác quá",ps:"Động",vi:"bỏ lỡ",ex:"错过机会 (lỡ cơ hội) / 错过时间 (lỡ giờ) / 错过航班 (lỡ chuyến bay)"},
{h:"错误",p:"cuòwù",hv:"thác ngộ",ps:"Danh/Tính",vi:"sai lầm",ex:"犯错误 (phạm lỗi) / 错误答案 (đáp án sai) / 改正错误 (sửa lỗi)"},
{h:"粗心",p:"cūxīn",hv:"thô tâm",ps:"Tính",vi:"cẩu thả",ex:"太粗心 (quá cẩu thả) / 粗心大意 (bất cẩn) / 粗心的人 (người bất cẩn)"},
{h:"答",p:"dá",hv:"đáp",ps:"Động",vi:"trả lời",ex:"答问题 (trả lời câu hỏi) / 答得对 (trả lời đúng) / 不回答 (không trả lời)"},
{h:"打招呼",p:"dǎzhāohu",hv:"đả chiêu hô",ps:"Động",vi:"chào hỏi",ex:"跟人打招呼 (chào người khác) / 打招呼方式 (cách chào) / 先打招呼 (chào trước)"},
{h:"答案",p:"dá’àn",hv:"đáp án",ps:"Danh",vi:"đáp án",ex:"正确答案 (đáp án đúng) / 写答案 (viết đáp án) / 找答案 (tìm đáp án)"},
{h:"大巴",p:"dàbā",hv:"đại ba",ps:"Danh",vi:"xe buýt lớn",ex:"坐大巴 (đi xe bus lớn) / 大巴车站 (bến xe) / 大巴票 (vé xe)"},
{h:"打败",p:"dǎbài",hv:"đả bại",ps:"Động",vi:"đánh bại",ex:"打败对手 (đánh bại đối thủ) / 被打败 (bị đánh bại) / 打败困难 (vượt khó)"},
{h:"大大",p:"dàdà",hv:"đại đại",ps:"Phó",vi:"rất, nhiều",ex:"大大提高 (tăng mạnh) / 大大减少 (giảm mạnh) / 大大影响 (ảnh hưởng lớn)"},
{h:"达到",p:"dádào",hv:"đạt đáo",ps:"Động",vi:"đạt tới",ex:"达到目标 (đạt mục tiêu) / 达到标准 (đạt chuẩn) / 达到要求 (đạt yêu cầu)"},
{h:"打工",p:"dǎgōng",hv:"đả công",ps:"Động",vi:"làm thuê",ex:"出去打工 (đi làm thuê) / 打工生活 (cuộc sống làm thuê) / 打工赚钱 (làm kiếm tiền)"},
{h:"戴",p:"dài",hv:"đới",ps:"Động",vi:"đeo (kính/mũ)",ex:"戴眼镜 (đeo kính) / 戴帽子 (đội mũ) / 戴口罩 (đeo khẩu trang)"},
{h:"待",p:"dāi",hv:"đãi",ps:"Động",vi:"ở lại",ex:"待一会儿 (ở một lát) / 待在家 (ở nhà) / 待几天 (ở vài ngày)"},
{h:"大夫",p:"dàifu",hv:"đại phu",ps:"Danh",vi:"bác sĩ",ex:"看大夫 (đi khám) / 大夫说 (bác sĩ nói) / 找大夫 (tìm bác sĩ)"},
{h:"袋子",p:"dàizi",hv:"đại tử",ps:"Danh",vi:"túi",ex:"塑料袋子 (túi nhựa) / 纸袋子 (túi giấy) / 拿袋子 (cầm túi)"},
{h:"大量",p:"dàliàng",hv:"đại lượng",ps:"Tính",vi:"số lượng lớn",ex:"大量信息 (nhiều thông tin) / 大量购买 (mua số lượng lớn) / 大量减少 (giảm mạnh)"},
{h:"当",p:"dāng",hv:"đương",ps:"Động/Giới",vi:"làm; khi",ex:"当老师 (làm giáo viên) / 当时 (lúc đó) / 当…的时候 (khi… )"},
{h:"当时",p:"dāngshí",hv:"đương thời",ps:"Danh",vi:"lúc đó",ex:"当时情况 (tình hình lúc đó) / 当时决定 (quyết định lúc đó) / 当时没有 (lúc đó không có)"},
{h:"单位",p:"dānwèi",hv:"đơn vị",ps:"Danh",vi:"đơn vị; cơ quan",ex:"工作单位 (cơ quan) / 单位名称 (tên đơn vị) / 单位领导 (lãnh đạo cơ quan)"},
{h:"倒",p:"dào",hv:"đảo",ps:"Động/Phó",vi:"đổ; ngược lại",ex:"倒水 (rót nước) / 倒垃圾 (đổ rác) / 倒过来 (lật ngược)"},
{h:"道",p:"dào",hv:"đạo",ps:"Danh/Lượng",vi:"đường; (lượng) món",ex:"一道菜 (một món) / 这道题 (bài này) / 道路 (đường xá)"},
{h:"刀",p:"dāo",hv:"đao",ps:"Danh",vi:"dao",ex:"水果刀 (dao gọt trái cây) / 菜刀 (dao bếp) / 一把刀 (một con dao)"},
{h:"到底",p:"dàodǐ",hv:"đáo để",ps:"Phó",vi:"rốt cuộc",ex:"到底怎么回事 (rốt cuộc chuyện gì) / 到底是谁 (rốt cuộc là ai) / 到底要不要 (rốt cuộc có hay không)"},
{h:"到来",p:"dàolái",hv:"đáo lai",ps:"Động",vi:"đến (thời điểm)",ex:"春天到来 (mùa xuân đến) / 新年到来 (năm mới đến) / 机会到来 (cơ hội đến)"},
{h:"道路",p:"dàolù",hv:"đạo lộ",ps:"Danh",vi:"đường xá",ex:"道路安全 (an toàn đường bộ) / 道路建设 (xây dựng đường) / 道路拥堵 (tắc đường)"},
{h:"道歉",p:"dàoqiàn",hv:"đạo khiểm",ps:"Động",vi:"xin lỗi",ex:"向…道歉 (xin lỗi ai) / 道歉信 (thư xin lỗi) / 公开道歉 (xin lỗi công khai)"},
{h:"导游",p:"dǎoyóu",hv:"đạo du",ps:"Danh/Động",vi:"hướng dẫn viên",ex:"旅游导游 (HDV du lịch) / 导游介绍 (HDV giới thiệu) / 请导游 (thuê HDV)"},
{h:"打扰",p:"dǎrǎo",hv:"đả nhiễu",ps:"Động",vi:"làm phiền",ex:"打扰一下 (làm phiền chút) / 不好意思打扰 (xin lỗi làm phiền) / 打扰你了 (làm phiền bạn rồi)"},
{h:"大赛",p:"dàsài",hv:"đại tái",ps:"Danh",vi:"cuộc thi lớn",ex:"全国大赛 (đại hội toàn quốc) / 大赛冠军 (vô địch) / 大赛规则 (luật cuộc thi)"},
{h:"大厅",p:"dàtīng",hv:"đại sảnh",ps:"Danh",vi:"đại sảnh",ex:"酒店大厅 (sảnh khách sạn) / 大厅里 (trong sảnh) / 大厅入口 (cửa vào sảnh)"},
{h:"打印",p:"dǎyìn",hv:"đả ấn",ps:"Động",vi:"in (tài liệu)",ex:"打印文件 (in tài liệu) / 打印出来 (in ra) / 打印服务 (dịch vụ in)"},
{h:"答应",p:"dāying",hv:"đáp ứng",ps:"Động",vi:"đồng ý, nhận lời",ex:"答应请求 (đồng ý yêu cầu) / 答应帮忙 (nhận lời giúp) / 不答应 (không đồng ý)"},
{h:"打印机",p:"dǎyìnjī",hv:"đả ấn cơ",ps:"Danh",vi:"máy in",ex:"买打印机 (mua máy in) / 打印机坏了 (máy in hỏng) / 打印机设置 (cài đặt máy in)"},
{h:"大约",p:"dàyuē",hv:"đại ước",ps:"Phó",vi:"khoảng",ex:"大约十分钟 (khoảng 10 phút) / 大约一百人 (khoảng 100 người) / 大约三公里 (khoảng 3km)"},
{h:"打折",p:"dǎzhé",hv:"đả chiết",ps:"Động",vi:"giảm giá",ex:"打折商品 (hàng giảm giá) / 八折 (giảm 20%) / 打折活动 (chương trình giảm giá)"},
{h:"打针",p:"dǎzhēn",hv:"đả châm",ps:"Động",vi:"tiêm",ex:"去打针 (đi tiêm) / 打预防针 (tiêm phòng) / 打针疼 (tiêm đau)"},
{h:"大自然",p:"dàzìrán",hv:"đại tự nhiên",ps:"Danh",vi:"thiên nhiên",ex:"保护大自然 (bảo vệ thiên nhiên) / 走进大自然 (hòa vào thiên nhiên) / 大自然风景 (cảnh thiên nhiên)"},
{h:"等",p:"děng",hv:"đẳng",ps:"Trợ/Lượng",vi:"đợi; v.v.",ex:"等一下 (đợi chút) / 等人 (đợi người) / 你等我 (bạn đợi tôi)"},
{h:"等到",p:"děngdào",hv:"đẳng đáo",ps:"Giới/Động",vi:"đợi đến khi",ex:"等到明天 (đợi đến mai) / 等到下班 (đợi tới tan ca) / 等到他来 (đợi tới khi anh ấy đến)"},
{h:"登机",p:"dēngjī",hv:"đăng cơ",ps:"Động",vi:"lên máy bay",ex:"登机口 (cổng lên máy bay) / 办理登机 (làm thủ tục lên máy bay) / 开始登机 (bắt đầu lên máy bay)"},
{h:"得意",p:"déyì",hv:"đắc ý",ps:"Tính",vi:"đắc ý",ex:"很得意 (rất đắc ý) / 得意的样子 (vẻ đắc ý) / 有点得意 (hơi đắc ý)"},
{h:"底",p:"dǐ",hv:"để",ps:"Danh",vi:"đáy",ex:"水底 (đáy nước) / 底下 (bên dưới) / 桌子底 (dưới bàn)"},
{h:"低",p:"dī",hv:"đê",ps:"Tính/Động",vi:"thấp; hạ",ex:"低价格 (giá thấp) / 温度低 (nhiệt độ thấp) / 降低 (hạ xuống)"},
{h:"电动车",p:"diàndòngchē",hv:"điện động xa",ps:"Danh",vi:"xe điện",ex:"骑电动车 (đi xe điện) / 电动车充电 (sạc xe điện) / 电动车牌照 (biển xe điện)"},
{h:"点名",p:"diǎnmíng",hv:"điểm danh",ps:"Động",vi:"điểm danh",ex:"老师点名 (thầy điểm danh) / 点名册 (sổ điểm danh) / 点名时间 (giờ điểm danh)"},
{h:"电视剧",p:"diànshìjù",hv:"điện thị kịch",ps:"Danh",vi:"phim truyền hình",ex:"看电视剧 (xem phim) / 电视剧演员 (diễn viên) / 电视剧剧情 (nội dung phim)"},
{h:"点头",p:"diǎntóu",hv:"điểm đầu",ps:"Động",vi:"gật đầu",ex:"点头同意 (gật đầu đồng ý) / 点头打招呼 (gật đầu chào) / 点点头 (gật gật đầu)"},
{h:"掉",p:"diào",hv:"điệu",ps:"Động",vi:"rơi; mất",ex:"掉下来 (rơi xuống) / 掉东西 (làm rơi đồ) / 掉头发 (rụng tóc)"},
{h:"调查",p:"diàochá",hv:"điều tra",ps:"Động",vi:"điều tra",ex:"调查情况 (điều tra tình hình) / 调查报告 (báo cáo điều tra) / 调查结果 (kết quả điều tra)"},
{h:"低价",p:"dījià",hv:"đê giá",ps:"Danh",vi:"giá thấp",ex:"低价商品 (hàng giá thấp) / 低价购买 (mua rẻ) / 低价策略 (chiến lược giá thấp)"},
{h:"订",p:"dìng",hv:"đính",ps:"Động",vi:"đặt (vé/phòng)",ex:"订票 (đặt vé) / 订房间 (đặt phòng) / 订餐 (đặt đồ ăn)"},
{h:"定",p:"dìng",hv:"định",ps:"Động",vi:"định, quyết định",ex:"决定定了 (quyết định rồi) / 定时间 (định giờ) / 定计划 (lập kế hoạch)"},
{h:"地球",p:"dìqiú",hv:"địa cầu",ps:"Danh",vi:"Trái Đất",ex:"地球上 (trên Trái Đất) / 保护地球 (bảo vệ Trái Đất) / 地球环境 (môi trường Trái Đất)"},
{h:"低温",p:"dīwēn",hv:"đê ôn",ps:"Danh",vi:"nhiệt độ thấp",ex:"低温天气 (thời tiết lạnh) / 低温环境 (môi trường nhiệt thấp) / 低温预警 (cảnh báo lạnh)"},
{h:"底下",p:"dǐxia",hv:"để hạ",ps:"Danh",vi:"bên dưới",ex:"桌子底下 (dưới bàn) / 山底下 (dưới chân núi) / 底下有人 (bên dưới có người)"},
{h:"低于",p:"dīyú",hv:"đê vu",ps:"Động",vi:"thấp hơn",ex:"低于标准 (thấp hơn chuẩn) / 低于平均 (thấp hơn TB) / 低于预期 (thấp hơn kỳ vọng)"},
{h:"地址",p:"dìzhǐ",hv:"địa chỉ",ps:"Danh",vi:"địa chỉ",ex:"家庭地址 (địa chỉ nhà) / 邮箱地址 (địa chỉ email) / 地址信息 (thông tin địa chỉ)"},
{h:"东部",p:"dōngbù",hv:"đông bộ",ps:"Danh",vi:"miền Đông",ex:"东部地区 (khu miền Đông) / 东部城市 (thành phố miền Đông) / 东部发展 (phát triển miền Đông)"},
{h:"动车",p:"dòngchē",hv:"động xa",ps:"Danh",vi:"tàu động lực (tàu nhanh)",ex:"坐动车 (đi tàu nhanh) / 动车站 (ga tàu nhanh) / 动车票 (vé tàu nhanh)"},
{h:"动作",p:"dòngzuò",hv:"động tác",ps:"Danh",vi:"động tác",ex:"动作快 (động tác nhanh) / 动作要领 (yếu lĩnh động tác) / 做动作 (làm động tác)"},
{h:"短信",p:"duǎnxìn",hv:"đoản tín",ps:"Danh",vi:"tin nhắn SMS",ex:"发短信 (gửi SMS) / 收短信 (nhận SMS) / 短信内容 (nội dung tin)"},
{h:"堵车",p:"dǔchē",hv:"đổ xa",ps:"Động",vi:"kẹt xe",ex:"路上堵车 (kẹt xe trên đường) / 又堵车了 (lại kẹt xe) / 堵车严重 (kẹt xe nặng)"},
{h:"队",p:"duì",hv:"đội",ps:"Danh/Lượng",vi:"đội",ex:"排队 (xếp hàng) / 一队人 (một đội người) / 足球队 (đội bóng)"},
{h:"对方",p:"duìfāng",hv:"đối phương",ps:"Danh",vi:"đối phương",ex:"对方公司 (công ty đối tác) / 对方同意 (đối phương đồng ý) / 对方意见 (ý kiến đối phương)"},
{h:"对面",p:"duìmiàn",hv:"đối diện",ps:"Danh",vi:"đối diện",ex:"在对面 (ở đối diện) / 对面楼 (tòa đối diện) / 对面的人 (người đối diện)"},
{h:"对于",p:"duìyú",hv:"đối vu",ps:"Giới",vi:"đối với",ex:"对于我来说 (đối với tôi) / 对于问题 (đối với vấn đề) / 对于孩子 (đối với trẻ)"},
{h:"队员",p:"duìyuán",hv:"đội viên",ps:"Danh",vi:"thành viên đội",ex:"队员名单 (danh sách đội viên) / 队员训练 (luyện tập đội) / 新队员 (đội viên mới)"},
{h:"队长",p:"duìzhǎng",hv:"đội trưởng",ps:"Danh",vi:"đội trưởng",ex:"队长安排 (đội trưởng sắp xếp) / 当队长 (làm đội trưởng) / 队长讲话 (đội trưởng nói)"},
{h:"度假",p:"dùjià",hv:"độ giả",ps:"Động",vi:"đi nghỉ",ex:"去度假 (đi nghỉ) / 度假村 (khu nghỉ dưỡng) / 度假计划 (kế hoạch nghỉ)"},
{h:"顿",p:"dùn",hv:"đốn",ps:"Lượng/Động",vi:"bữa; dừng một chút",ex:"一顿饭 (một bữa) / 骂一顿 (mắng một trận) / 停顿一下 (dừng chút)"},
{h:"多么",p:"duōme",hv:"đa ma",ps:"Phó",vi:"biết bao",ex:"多么好 (tốt biết bao) / 多么漂亮 (đẹp biết bao) / 多么重要 (quan trọng biết bao)"},
{h:"多数",p:"duōshù",hv:"đa số",ps:"Danh",vi:"đa số",ex:"多数人 (đa số người) / 多数情况 (đa số trường hợp) / 占多数 (chiếm đa số)"},
{h:"多样",p:"duōyàng",hv:"đa dạng",ps:"Tính",vi:"đa dạng",ex:"形式多样 (hình thức đa dạng) / 多样选择 (lựa chọn đa dạng) / 多样文化 (văn hóa đa dạng)"},
{h:"读者",p:"dúzhě",hv:"độc giả",ps:"Danh",vi:"độc giả",ex:"读者来信 (thư độc giả) / 读者人数 (số độc giả) / 面向读者 (hướng tới độc giả)"},
{h:"肚子",p:"dùzi",hv:"đỗ tử",ps:"Danh",vi:"bụng",ex:"肚子疼 (đau bụng) / 饿肚子 (đói bụng) / 肚子饿了 (bụng đói rồi)"},
{h:"而",p:"ér",hv:"nhi",ps:"Liên",vi:"mà, còn",ex:"努力而成功 (nỗ lực mà thành công) / 简单而有效 (đơn giản mà hiệu quả) / 大而明亮 (to và sáng)"},
{h:"儿童",p:"értóng",hv:"nhi đồng",ps:"Danh",vi:"trẻ em",ex:"儿童医院 (bệnh viện nhi) / 儿童教育 (giáo dục trẻ em) / 儿童玩具 (đồ chơi trẻ em)"},
{h:"法",p:"fǎ",hv:"pháp",ps:"Danh",vi:"pháp luật; cách",ex:"法律 (pháp luật) / 方法 (phương pháp) / 想法 (cách nghĩ)"},
{h:"发出",p:"fāchū",hv:"phát xuất",ps:"Động",vi:"phát ra",ex:"发出声音 (phát ra âm thanh) / 发出通知 (ra thông báo) / 发出信号 (phát tín hiệu)"},
{h:"法律",p:"fǎlǜ",hv:"pháp luật",ps:"Danh",vi:"pháp luật",ex:"法律规定 (quy định pháp luật) / 法律责任 (trách nhiệm pháp lý) / 了解法律 (hiểu luật)"},
{h:"烦",p:"fán",hv:"phiền",ps:"Tính/Động",vi:"phiền; bực",ex:"真烦 (phiền thật) / 烦死了 (phiền chết đi được) / 别烦我 (đừng làm phiền)"},
{h:"反对",p:"fǎnduì",hv:"phản đối",ps:"Động",vi:"phản đối",ex:"反对意见 (ý kiến phản đối) / 表示反对 (bày tỏ phản đối) / 反对计划 (phản đối kế hoạch)"},
{h:"房东",p:"fángdōng",hv:"phòng đông",ps:"Danh",vi:"chủ nhà",ex:"房东太太 (bà chủ nhà) / 问房东 (hỏi chủ nhà) / 房东要求 (yêu cầu của chủ nhà)"},
{h:"方面",p:"fāngmiàn",hv:"phương diện",ps:"Danh",vi:"phương diện",ex:"学习方面 (mặt học tập) / 工作方面 (mặt công việc) / 各个方面 (mọi mặt)"},
{h:"放弃",p:"fàngqì",hv:"phóng khí",ps:"Động",vi:"từ bỏ",ex:"放弃机会 (từ bỏ cơ hội) / 放弃治疗 (từ bỏ điều trị) / 放弃计划 (từ bỏ kế hoạch)"},
{h:"方式",p:"fāngshì",hv:"phương thức",ps:"Danh",vi:"phương thức",ex:"工作方式 (cách làm việc) / 生活方式 (lối sống) / 付款方式 (cách thanh toán)"},
{h:"放松",p:"fàngsōng",hv:"phóng tùng",ps:"Động",vi:"thư giãn",ex:"放松一下 (thư giãn chút) / 放松心情 (thả lỏng tâm trạng) / 放松身体 (thư giãn cơ thể)"},
{h:"房租",p:"fángzū",hv:"phòng tô",ps:"Danh",vi:"tiền thuê nhà",ex:"交房租 (trả tiền thuê) / 房租太贵 (tiền thuê đắt) / 房租合同 (hợp đồng thuê)"},
{h:"烦恼",p:"fánnǎo",hv:"phiền não",ps:"Tính",vi:"phiền não",ex:"烦恼的事 (việc phiền) / 没烦恼 (không phiền) / 烦恼情绪 (tâm trạng phiền)"},
{h:"翻译",p:"fānyì",hv:"phiên dịch",ps:"Động/Danh",vi:"dịch",ex:"翻译成中文 (dịch sang TQ) / 做翻译 (làm phiên dịch) / 翻译软件 (phần mềm dịch)"},
{h:"发送",p:"fāsòng",hv:"phát tống",ps:"Động",vi:"gửi (tin)",ex:"发送邮件 (gửi mail) / 发送信息 (gửi tin) / 发送文件 (gửi file)"},
{h:"费",p:"fèi",hv:"phí",ps:"Danh/Động",vi:"phí; tốn",ex:"学费 (học phí) / 费时间 (tốn thời gian) / 费用 (chi phí)"},
{h:"费用",p:"fèiyong",hv:"phí dụng",ps:"Danh",vi:"chi phí",ex:"交通费用 (chi phí đi lại) / 医疗费用 (chi phí y tế) / 费用清单 (bảng chi phí)"},
{h:"份",p:"fèn",hv:"phần",ps:"Lượng",vi:"phần, suất",ex:"一份菜单 (một menu) / 一份工作 (một công việc) / 一份礼物 (một món quà)"},
{h:"丰富",p:"fēngfù",hv:"phong phú",ps:"Tính",vi:"phong phú",ex:"内容丰富 (nội dung phong phú) / 经验丰富 (kinh nghiệm phong phú) / 丰富多彩 (đa dạng sắc màu)"},
{h:"风景",p:"fēngjǐng",hv:"phong cảnh",ps:"Danh",vi:"phong cảnh",ex:"风景很好 (cảnh đẹp) / 看风景 (ngắm cảnh) / 风景区 (khu thắng cảnh)"},
{h:"分数",p:"fēnshù",hv:"phân số",ps:"Danh",vi:"điểm số",ex:"考试分数 (điểm thi) / 分数很高 (điểm cao) / 提高分数 (tăng điểm)"},
{h:"分为",p:"fēnwéi",hv:"phân vi",ps:"Động",vi:"chia thành",ex:"分为两部分 (chia 2 phần) / 分为三组 (chia 3 nhóm) / 分为几个阶段 (chia vài giai đoạn)"},
{h:"否则",p:"fǒuzé",hv:"phủ tắc",ps:"Liên",vi:"nếu không thì",ex:"快点，否则迟到 (nhanh lên, không thì trễ) / 听话，否则… (nghe lời, không thì…) / 做好，否则麻烦 (làm tốt, không thì phiền)"},
{h:"幅",p:"fú",hv:"phúc",ps:"Lượng",vi:"bức (tranh)",ex:"一幅画 (một bức tranh) / 两幅照片 (hai bức ảnh) / 一幅地图 (một bản đồ)"},
{h:"付",p:"fù",hv:"phó",ps:"Động",vi:"trả (tiền)",ex:"付钱 (trả tiền) / 付款方式 (cách thanh toán) / 付房租 (trả tiền nhà)"},
{h:"符合",p:"fúhé",hv:"phù hợp",ps:"Động",vi:"phù hợp",ex:"符合条件 (phù hợp điều kiện) / 符合标准 (đúng chuẩn) / 不符合要求 (không đúng yêu cầu)"},
{h:"父母",p:"fùmǔ",hv:"phụ mẫu",ps:"Danh",vi:"bố mẹ",ex:"照顾父母 (chăm bố mẹ) / 父母同意 (bố mẹ đồng ý) / 父母的话 (lời bố mẹ)"},
{h:"父女",p:"fùnǚ",hv:"phụ nữ",ps:"Danh",vi:"cha và con gái",ex:"父女关系 (quan hệ cha-con gái) / 父女俩 (hai cha con) / 父女合影 (ảnh chụp chung)"},
{h:"父亲",p:"fùqīn",hv:"phụ thân",ps:"Danh",vi:"bố",ex:"我的父亲 (bố tôi) / 父亲节 (Ngày của Cha) / 父亲工作 (công việc của bố)"},
{h:"复印",p:"fùyìn",hv:"phục ấn",ps:"Động",vi:"photocopy",ex:"复印文件 (photo tài liệu) / 复印一份 (photo một bản) / 复印店 (tiệm photo)"},
{h:"复杂",p:"fùzá",hv:"phức tạp",ps:"Tính",vi:"phức tạp",ex:"情况复杂 (tình hình phức tạp) / 复杂问题 (vấn đề phức tạp) / 关系复杂 (quan hệ phức tạp)"},
{h:"负责",p:"fùzé",hv:"phụ trách",ps:"Động/Tính",vi:"chịu trách nhiệm",ex:"负责工作 (phụ trách việc) / 对…负责 (chịu trách nhiệm về…) / 负责人 (người phụ trách)"},
{h:"负责人",p:"fùzérén",hv:"phụ trách nhân",ps:"Danh",vi:"người phụ trách",ex:"项目负责人 (phụ trách dự án) / 负责人电话 (SĐT phụ trách) / 联系负责人 (liên hệ phụ trách)"},
{h:"父子",p:"fùzǐ",hv:"phụ tử",ps:"Danh",vi:"cha và con trai",ex:"父子关系 (quan hệ cha-con trai) / 父子俩 (hai cha con) / 父子照片 (ảnh cha con)"},
{h:"改",p:"gǎi",hv:"cải",ps:"Động",vi:"sửa, thay đổi",ex:"改错 (sửa sai) / 改时间 (đổi giờ) / 改一下 (sửa chút)"},
{h:"改变",p:"gǎibiàn",hv:"cải biến",ps:"Động",vi:"thay đổi",ex:"改变计划 (đổi kế hoạch) / 改变习惯 (đổi thói quen) / 改变想法 (đổi suy nghĩ)"},
{h:"赶",p:"gǎn",hv:"cản",ps:"Động",vi:"đi gấp; đuổi",ex:"赶时间 (chạy giờ) / 赶车 (đuổi kịp xe) / 赶走 (đuổi đi)"},
{h:"敢",p:"gǎn",hv:"cảm",ps:"Động",vi:"dám",ex:"不敢说 (không dám nói) / 敢做敢当 (dám làm dám chịu) / 你敢吗 (bạn dám không)"},
{h:"感",p:"gǎn",hv:"cảm",ps:"Hậu tố",vi:"cảm giác/…",ex:"亲切感 (cảm giác thân thiện) / 安全感 (cảm giác an toàn) / 责任感 (tinh thần trách nhiệm)"},
{h:"干",p:"gān",hv:"can",ps:"Tính/Danh",vi:"khô",ex:"干衣服 (quần áo khô) / 干毛巾 (khăn khô) / 天气很干 (thời tiết hanh)"},
{h:"干杯",p:"gānbēi",hv:"can bôi",ps:"Động",vi:"cạn ly",ex:"一起干杯 (cùng cạn ly) / 干杯！(dzô!) / 跟大家干杯 (cạn ly với mọi người)"},
{h:"感动",p:"gǎndòng",hv:"cảm động",ps:"Tính/Động",vi:"cảm động",ex:"很感动 (rất cảm động) / 感动的故事 (chuyện cảm động) / 让我感动 (làm tôi cảm động)"},
{h:"钢琴",p:"gāngqín",hv:"cương cầm",ps:"Danh",vi:"đàn piano",ex:"弹钢琴 (chơi piano) / 钢琴课 (lớp piano) / 钢琴声音 (âm piano)"},
{h:"干活儿",p:"gànhuór",hv:"can hoạt nhi",ps:"Động",vi:"làm việc (tay chân)",ex:"干活儿累 (làm việc mệt) / 去干活儿 (đi làm) / 干活儿的人 (người lao động)"},
{h:"赶紧",p:"gǎnjǐn",hv:"cản khẩn",ps:"Phó",vi:"mau lên",ex:"赶紧走 (mau đi) / 赶紧写 (mau viết) / 赶紧回来 (mau về)"},
{h:"感觉",p:"gǎnjué",hv:"cảm giác",ps:"Danh/Động",vi:"cảm thấy; cảm giác",ex:"感觉不错 (cảm thấy ổn) / 感觉累 (cảm thấy mệt) / 给人感觉 (tạo cảm giác)"},
{h:"赶快",p:"gǎnkuài",hv:"cản khoái",ps:"Phó",vi:"nhanh lên",ex:"赶快起床 (nhanh dậy) / 赶快去 (nhanh đi) / 赶快回答 (nhanh trả lời)"},
{h:"感情",p:"gǎnqíng",hv:"cảm tình",ps:"Danh",vi:"tình cảm",ex:"感情很好 (tình cảm tốt) / 感情问题 (vấn đề tình cảm) / 培养感情 (bồi dưỡng tình cảm)"},
{h:"感人",p:"gǎnrén",hv:"cảm nhân",ps:"Tính",vi:"cảm động lòng người",ex:"感人的电影 (phim cảm động) / 感人故事 (chuyện cảm động) / 很感人 (rất cảm động)"},
{h:"赶上",p:"gǎnshàng",hv:"cản thượng",ps:"Động",vi:"kịp; đuổi kịp",ex:"赶上火车 (kịp tàu) / 赶上时间 (kịp giờ) / 赶上进度 (kịp tiến độ)"},
{h:"感受",p:"gǎnshòu",hv:"cảm thụ",ps:"Danh/Động",vi:"cảm nhận",ex:"生活感受 (cảm nhận cuộc sống) / 亲身感受 (trải nghiệm trực tiếp) / 感受一下 (cảm nhận thử)"},
{h:"感谢",p:"gǎnxiè",hv:"cảm tạ",ps:"Động",vi:"cảm ơn",ex:"感谢帮助 (cảm ơn giúp) / 非常感谢 (vô cùng cảm ơn) / 感谢信 (thư cảm ơn)"},
{h:"高价",p:"gāojià",hv:"cao giá",ps:"Danh",vi:"giá cao",ex:"高价商品 (hàng giá cao) / 高价购买 (mua giá cao) / 高价房租 (tiền thuê cao)"},
{h:"高考",p:"gāokǎo",hv:"cao khảo",ps:"Danh",vi:"kỳ thi ĐH (TQ)",ex:"参加高考 (dự thi cao khảo) / 高考成绩 (điểm cao khảo) / 高考压力 (áp lực thi)"},
{h:"高速",p:"gāosù",hv:"cao tốc",ps:"Tính",vi:"tốc độ cao; cao tốc",ex:"高速公路 (đường cao tốc) / 高速发展 (phát triển nhanh) / 高速列车 (tàu tốc độ cao)"},
{h:"高温",p:"gāowēn",hv:"cao ôn",ps:"Danh",vi:"nhiệt độ cao",ex:"高温天气 (thời tiết nóng) / 高温预警 (cảnh báo nóng) / 高温环境 (môi trường nóng)"},
{h:"高于",p:"gāoyú",hv:"cao vu",ps:"Động",vi:"cao hơn",ex:"高于标准 (cao hơn chuẩn) / 高于平均 (cao hơn TB) / 高于预期 (cao hơn kỳ vọng)"},
{h:"各",p:"gè",hv:"các",ps:"Đại/Phó",vi:"mỗi, các",ex:"各位 (các vị) / 各种 (các loại) / 各自 (mỗi người)"},
{h:"胳膊",p:"gēbo",hv:"cách bạc",ps:"Danh",vi:"cánh tay",ex:"胳膊疼 (đau tay) / 右胳膊 (tay phải) / 抬胳膊 (giơ tay)"},
{h:"各地",p:"gèdì",hv:"các địa",ps:"Danh",vi:"khắp nơi",ex:"全国各地 (khắp cả nước) / 各地美食 (ẩm thực các nơi) / 来自各地 (đến từ khắp nơi)"},
{h:"各个",p:"gègè",hv:"các cá",ps:"Đại/Phó",vi:"từng cái",ex:"各个方面 (mọi mặt) / 各个部门 (từng phòng ban) / 各个国家 (từng quốc gia)"},
{h:"共",p:"gòng",hv:"cộng",ps:"Phó",vi:"tổng cộng; cùng",ex:"一共 (tổng cộng) / 共同 (cùng nhau) / 共十个人 (tổng 10 người)"},
{h:"工厂",p:"gōngchǎng",hv:"công xưởng",ps:"Danh",vi:"nhà máy",ex:"工厂工人 (công nhân nhà máy) / 工厂生产 (sản xuất nhà máy) / 工厂附近 (gần nhà máy)"},
{h:"功夫",p:"gōngfu",hv:"công phu",ps:"Danh",vi:"công phu; thời gian/công sức",ex:"下功夫 (bỏ công sức) / 有功夫 (có thời gian) / 功夫茶 (trà công phu)"},
{h:"公共",p:"gōnggòng",hv:"công cộng",ps:"Tính",vi:"công cộng",ex:"公共场所 (nơi công cộng) / 公共交通 (giao thông công cộng) / 公共服务 (dịch vụ công)"},
{h:"功课",p:"gōngkè",hv:"công khóa",ps:"Danh",vi:"bài học/bài tập",ex:"做功课 (làm bài) / 功课很多 (nhiều bài) / 功课时间 (thời gian học)"},
{h:"公里",p:"gōnglǐ",hv:"công lý",ps:"Lượng",vi:"km",ex:"三公里 (3 km) / 公里数 (số km) / 两公里路 (đường 2 km)"},
{h:"公路",p:"gōnglù",hv:"công lộ",ps:"Danh",vi:"đường cái",ex:"公路交通 (giao thông đường bộ) / 公路建设 (xây đường) / 公路上 (trên đường cái)"},
{h:"工人",p:"gōngrén",hv:"công nhân",ps:"Danh",vi:"công nhân",ex:"工人工资 (lương công nhân) / 工人宿舍 (ký túc công nhân) / 工人上班 (công nhân đi làm)"},
{h:"共同",p:"gòngtóng",hv:"cộng đồng",ps:"Tính",vi:"chung, cùng",ex:"共同努力 (cùng cố gắng) / 共同目标 (mục tiêu chung) / 共同兴趣 (sở thích chung)"},
{h:"工资",p:"gōngzī",hv:"công tư",ps:"Danh",vi:"lương",ex:"发工资 (phát lương) / 工资太低 (lương thấp) / 工资水平 (mức lương)"},
{h:"够",p:"gòu",hv:"cấu",ps:"Động/Phó",vi:"đủ",ex:"钱够了 (tiền đủ rồi) / 够不够 (đủ không) / 够大 (đủ lớn)"},
{h:"购买",p:"gòumǎi",hv:"cấu mại",ps:"Động",vi:"mua",ex:"购买商品 (mua hàng) / 购买力 (sức mua) / 购买记录 (lịch sử mua)"},
{h:"购物",p:"gòuwù",hv:"cấu vật",ps:"Động",vi:"mua sắm",ex:"购物中心 (TT mua sắm) / 网上购物 (mua online) / 购物清单 (danh sách mua)"},
{h:"挂",p:"guà",hv:"quải",ps:"Động",vi:"treo; cúp máy",ex:"挂衣服 (treo đồ) / 挂电话 (cúp máy) / 挂在墙上 (treo lên tường)"},
{h:"管",p:"guǎn",hv:"quản",ps:"Động/Danh",vi:"quản; ống",ex:"管孩子 (quản con) / 不管 (mặc kệ) / 水管 (ống nước)"},
{h:"逛",p:"guàng",hv:"quảng",ps:"Động",vi:"đi dạo/mua sắm",ex:"逛街 (dạo phố) / 逛商场 (dạo TTTM) / 逛一逛 (đi dạo chút)"},
{h:"光",p:"guāng",hv:"quang",ps:"Danh/Tính/Phó",vi:"ánh sáng; chỉ",ex:"阳光 (ánh nắng) / 光是… (chỉ là…) / 光线 (ánh sáng)"},
{h:"广播",p:"guǎngbō",hv:"quảng bá",ps:"Động/Danh",vi:"phát thanh; phát",ex:"广播节目 (chương trình radio) / 广播通知 (thông báo phát) / 校园广播 (loa trường)"},
{h:"广告",p:"guǎnggào",hv:"quảng cáo",ps:"Danh",vi:"quảng cáo",ex:"看广告 (xem quảng cáo) / 广告牌 (bảng QC) / 广告公司 (công ty QC)"},
{h:"关键",p:"guānjiàn",hv:"quan kiện",ps:"Danh/Tính",vi:"then chốt",ex:"关键问题 (vấn đề then chốt) / 关键时刻 (thời khắc then chốt) / 关键因素 (yếu tố then chốt)"},
{h:"观看",p:"guānkàn",hv:"quan khán",ps:"Động",vi:"xem",ex:"观看比赛 (xem trận) / 观看视频 (xem video) / 观看人数 (lượng người xem)"},
{h:"管理",p:"guǎnlǐ",hv:"quản lý",ps:"Động",vi:"quản lý",ex:"管理公司 (quản lý công ty) / 管理制度 (chế độ quản lý) / 时间管理 (quản lý thời gian)"},
{h:"观众",p:"guānzhòng",hv:"quan chúng",ps:"Danh",vi:"khán giả",ex:"现场观众 (khán giả tại chỗ) / 观众席 (ghế khán giả) / 观众很多 (rất đông)"},
{h:"规定",p:"guīdìng",hv:"quy định",ps:"Động/Danh",vi:"quy định",ex:"公司规定 (quy định công ty) / 按规定 (theo quy định) / 规定时间 (thời gian quy định)"},
{h:"估计",p:"gūjì",hv:"cô kế",ps:"Động",vi:"ước chừng",ex:"估计时间 (ước thời gian) / 我估计… (tôi đoán…) / 估计不够 (ước không đủ)"},
{h:"顾客",p:"gùkè",hv:"cố khách",ps:"Danh",vi:"khách hàng",ex:"顾客满意 (khách hài lòng) / 顾客服务 (dịch vụ KH) / 老顾客 (khách quen)"},
{h:"鼓励",p:"gǔlì",hv:"cổ lệ",ps:"Động",vi:"khích lệ",ex:"鼓励学生 (khích lệ HS) / 鼓励的话 (lời động viên) / 受到鼓励 (được động viên)"},
{h:"姑娘",p:"gūniang",hv:"cô nương",ps:"Danh",vi:"cô gái",ex:"小姑娘 (cô bé) / 姑娘们 (các cô gái) / 那位姑娘 (cô kia)"},
{h:"过程",p:"guòchéng",hv:"quá trình",ps:"Danh",vi:"quá trình",ex:"学习过程 (quá trình học) / 工作过程 (quá trình làm) / 过程复杂 (quá trình phức tạp)"},
{h:"国籍",p:"guójí",hv:"quốc tịch",ps:"Danh",vi:"quốc tịch",ex:"中国国籍 (quốc tịch TQ) / 国籍问题 (vấn đề quốc tịch) / 填国籍 (điền quốc tịch)"},
{h:"国际",p:"guójì",hv:"quốc tế",ps:"Danh/Tính",vi:"quốc tế",ex:"国际比赛 (thi đấu quốc tế) / 国际机场 (sân bay QT) / 国际新闻 (tin quốc tế)"},
{h:"果汁",p:"guǒzhī",hv:"quả trấp",ps:"Danh",vi:"nước ép",ex:"喝果汁 (uống nước ép) / 橙汁果汁 (nước cam) / 新鲜果汁 (nước ép tươi)"},
{h:"故意",p:"gùyì",hv:"cố ý",ps:"Phó",vi:"cố tình",ex:"故意迟到 (cố tình trễ) / 不是故意的 (không cố ý) / 故意不说 (cố tình không nói)"},
{h:"害羞",p:"hàixiū",hv:"hại tu",ps:"Tính",vi:"ngại ngùng",ex:"有点害羞 (hơi ngại) / 害羞的样子 (vẻ ngại) / 不害羞 (không ngại)"},
{h:"海洋",p:"hǎiyáng",hv:"hải dương",ps:"Danh",vi:"đại dương",ex:"海洋环境 (môi trường biển) / 海洋动物 (động vật biển) / 海洋公园 (công viên biển)"},
{h:"汗",p:"hàn",hv:"hãn",ps:"Danh",vi:"mồ hôi",ex:"出汗 (toát mồ hôi) / 汗水 (mồ hôi) / 满头大汗 (mồ hôi nhễ nhại)"},
{h:"喊",p:"hǎn",hv:"hảm",ps:"Động",vi:"hét/gọi to",ex:"喊名字 (gọi tên) / 大声喊 (hét lớn) / 喊我一下 (gọi tôi)"},
{h:"航班",p:"hángbān",hv:"hàng ban",ps:"Danh",vi:"chuyến bay",ex:"航班号 (số chuyến) / 航班延误 (trễ chuyến) / 查询航班 (tra chuyến bay)"},
{h:"寒假",p:"hánjià",hv:"hàn giả",ps:"Danh",vi:"nghỉ đông",ex:"寒假作业 (bài nghỉ đông) / 放寒假 (nghỉ đông) / 寒假计划 (kế hoạch nghỉ)"},
{h:"寒冷",p:"hánlěng",hv:"hàn lãnh",ps:"Tính",vi:"lạnh giá",ex:"天气寒冷 (thời tiết lạnh) / 寒冷地区 (vùng lạnh) / 寒冷的冬天 (mùa đông lạnh)"},
{h:"好处",p:"hǎochù",hv:"hảo xứ",ps:"Danh",vi:"lợi ích",ex:"有什么好处 (có lợi gì) / 好处很多 (nhiều lợi ích) / 对身体有好处 (tốt cho sức khỏe)"},
{h:"好好",p:"hǎohǎo",hv:"hảo hảo",ps:"Phó/Tính",vi:"đàng hoàng; tốt",ex:"好好学习 (học cho tốt) / 好好休息 (nghỉ cho tốt) / 好好说 (nói đàng hoàng)"},
{h:"好笑",p:"hǎoxiào",hv:"hảo tiếu",ps:"Tính",vi:"buồn cười",ex:"很好笑 (rất buồn cười) / 好笑的事 (việc buồn cười) / 一点不好笑 (chẳng buồn cười)"},
{h:"合格",p:"hégé",hv:"hợp cách",ps:"Tính",vi:"đạt chuẩn",ex:"合格产品 (sản phẩm đạt) / 合格证 (giấy đạt chuẩn) / 不合格 (không đạt)"},
{h:"盒子",p:"hézi",hv:"hạp tử",ps:"Danh",vi:"cái hộp",ex:"一个盒子 (một cái hộp) / 盒子里 (trong hộp) / 打开盒子 (mở hộp)"},
{h:"红包",p:"hóngbāo",hv:"hồng bao",ps:"Danh",vi:"lì xì",ex:"发红包 (phát lì xì) / 收红包 (nhận lì xì) / 红包钱 (tiền lì xì)"},
{h:"厚",p:"hòu",hv:"hậu",ps:"Tính",vi:"dày",ex:"很厚 (rất dày) / 厚衣服 (áo dày) / 书很厚 (sách dày)"},
{h:"后悔",p:"hòuhuǐ",hv:"hậu hối",ps:"Động",vi:"hối hận",ex:"后悔了 (hối hận rồi) / 不后悔 (không hối hận) / 后悔决定 (hối hận quyết định)"},
{h:"坏处",p:"huàichù",hv:"hoại xứ",ps:"Danh",vi:"tác hại",ex:"有什么坏处 (có hại gì) / 坏处很多 (nhiều tác hại) / 对身体坏处 (hại sức khỏe)"},
{h:"怀疑",p:"huáiyí",hv:"hoài nghi",ps:"Động",vi:"nghi ngờ",ex:"怀疑别人 (nghi người khác) / 怀疑自己 (nghi bản thân) / 表示怀疑 (tỏ nghi ngờ)"},
{h:"话剧",p:"huàjù",hv:"thoại kịch",ps:"Danh",vi:"kịch nói",ex:"看话剧 (xem kịch) / 话剧演员 (diễn viên kịch) / 话剧表演 (biểu diễn kịch)"},
{h:"环保",p:"huánbǎo",hv:"hoàn bảo",ps:"Danh/Tính",vi:"bảo vệ môi trường",ex:"环保产品 (sản phẩm xanh) / 环保意识 (ý thức BVMT) / 环保活动 (hoạt động BVMT)"},
{h:"换乘",p:"huànchéng",hv:"hoán thừa",ps:"Động",vi:"chuyển tuyến",ex:"换乘地铁 (đổi tàu điện) / 换乘站 (ga trung chuyển) / 换乘路线 (tuyến chuyển)"},
{h:"回复",p:"huífù",hv:"hồi phục",ps:"Động",vi:"trả lời; hồi phục",ex:"回复消息 (trả lời tin) / 回复邮件 (trả lời mail) / 快点回复 (trả lời nhanh)"},
{h:"回信",p:"huíxìn",hv:"hồi tín",ps:"Động/Danh",vi:"hồi âm",ex:"给他回信 (hồi âm cho anh ấy) / 回信内容 (nội dung hồi âm) / 及时回信 (hồi âm kịp)"},
{h:"回忆",p:"huíyì",hv:"hồi ức",ps:"Động",vi:"hồi tưởng",ex:"回忆过去 (nhớ quá khứ) / 美好回忆 (kỷ niệm đẹp) / 回忆一下 (nhớ lại chút)"},
{h:"会员",p:"huìyuán",hv:"hội viên",ps:"Danh",vi:"hội viên",ex:"会员卡 (thẻ hội viên) / 会员价 (giá hội viên) / 会员服务 (dịch vụ hội viên)"},
{h:"互联网",p:"hùliánwǎng",hv:"hỗ liên võng",ps:"Danh",vi:"Internet",ex:"互联网公司 (công ty internet) / 互联网时代 (thời đại internet) / 互联网服务 (dịch vụ internet)"},
{h:"活",p:"huó",hv:"hoạt",ps:"Động/Tính/Danh",vi:"sống; linh hoạt",ex:"生活 (cuộc sống) / 活下去 (sống tiếp) / 灵活 (linh hoạt)"},
{h:"货",p:"huò",hv:"hóa",ps:"Danh",vi:"hàng hóa",ex:"货物 (hàng hóa) / 进货 (nhập hàng) / 发货 (giao hàng)"},
{h:"火",p:"huǒ",hv:"hỏa",ps:"Danh/Tính",vi:"lửa; nóng",ex:"着火 (bốc cháy) / 火很大 (lửa lớn) / 火车 (tàu hỏa)"},
{h:"获得",p:"huòdé",hv:"hoạch đắc",ps:"Động",vi:"đạt được",ex:"获得机会 (được cơ hội) / 获得成功 (đạt thành công) / 获得奖励 (nhận thưởng)"},
{h:"活动",p:"huódòng",hv:"hoạt động",ps:"Danh/Động",vi:"hoạt động",ex:"参加活动 (tham gia) / 活动时间 (thời gian) / 活动地点 (địa điểm)"},
{h:"获奖",p:"huòjiǎng",hv:"hoạch thưởng",ps:"Động",vi:"đoạt giải",ex:"获奖名单 (danh sách đoạt) / 获奖作品 (tác phẩm đoạt) / 获奖感言 (phát biểu nhận giải)"},
{h:"活泼",p:"huópō",hv:"hoạt bát",ps:"Tính",vi:"hoạt bát",ex:"性格活泼 (tính cách hoạt bát) / 活泼可爱 (hoạt bát đáng yêu) / 很活泼 (rất hoạt bát)"},
{h:"获取",p:"huòqǔ",hv:"hoạch thủ",ps:"Động",vi:"lấy/thu thập",ex:"获取信息 (thu thập thông tin) / 获取数据 (lấy dữ liệu) / 获取机会 (giành cơ hội)"},
{h:"忽然",p:"hūrán",hv:"hốt nhiên",ps:"Phó",vi:"bỗng nhiên",ex:"忽然下雨 (bỗng mưa) / 忽然想起 (bỗng nhớ) / 忽然出现 (bỗng xuất hiện)"},
{h:"护士",p:"hùshi",hv:"hộ sĩ",ps:"Danh",vi:"y tá",ex:"护士站 (quầy y tá) / 护士照顾 (y tá chăm) / 当护士 (làm y tá)"},
{h:"互相",p:"hùxiāng",hv:"hỗ tương",ps:"Phó",vi:"lẫn nhau",ex:"互相帮助 (giúp nhau) / 互相理解 (hiểu nhau) / 互相学习 (học nhau)"},
{h:"既",p:"jì",hv:"ký",ps:"Phó/Liên",vi:"vừa… vừa…",ex:"既…又… (vừa… vừa…) / 既然 (đã vậy thì) / 既有…也有… (vừa có… cũng có…)"},
{h:"寄",p:"jì",hv:"ký",ps:"Động",vi:"gửi",ex:"寄信 (gửi thư) / 寄包裹 (gửi bưu kiện) / 寄快递 (gửi chuyển phát)"},
{h:"假",p:"jiǎ",hv:"giả",ps:"Tính",vi:"giả",ex:"假钱 (tiền giả) / 假消息 (tin giả) / 假的 (đồ giả)"},
{h:"加班",p:"jiābān",hv:"gia ban",ps:"Động",vi:"tăng ca",ex:"今天加班 (hôm nay tăng ca) / 加班费 (tiền tăng ca) / 不想加班 (không muốn tăng ca)"},
{h:"价格",p:"jiàgé",hv:"giá cách",ps:"Danh",vi:"giá cả",ex:"价格很贵 (giá đắt) / 价格便宜 (giá rẻ) / 价格变化 (biến động giá)"},
{h:"家具",p:"jiājù",hv:"gia cụ",ps:"Danh",vi:"đồ nội thất",ex:"买家具 (mua nội thất) / 家具店 (cửa hàng nội thất) / 家具设计 (thiết kế nội thất)"},
{h:"加快",p:"jiākuài",hv:"gia khoái",ps:"Động",vi:"tăng nhanh",ex:"加快速度 (tăng tốc) / 加快进度 (đẩy tiến độ) / 加快发展 (tăng phát triển)"},
{h:"减",p:"jiǎn",hv:"giảm",ps:"Động",vi:"giảm",ex:"减肥 (giảm cân) / 减少 (giảm bớt) / 减价格 (giảm giá)"},
{h:"降",p:"jiàng",hv:"giáng",ps:"Động",vi:"hạ xuống",ex:"降低 (hạ thấp) / 降价 (hạ giá) / 降温 (hạ nhiệt)"},
{h:"奖",p:"jiǎng",hv:"tưởng",ps:"Danh/Động",vi:"giải thưởng; thưởng",ex:"领奖 (nhận giải) / 奖金 (tiền thưởng) / 奖品 (phần thưởng)"},
{h:"江",p:"jiāng",hv:"giang",ps:"Danh",vi:"sông lớn",ex:"长江 (Trường Giang) / 江边 (bờ sông) / 江水 (nước sông)"},
{h:"将",p:"jiāng",hv:"tương",ps:"Giới/Phó",vi:"sẽ; đem",ex:"将来 (tương lai) / 将要 (sắp) / 将…放在… (đem… đặt vào…)"}
];

export const HSK5_ALL = [
{h:"唉",p:"ài",hv:"ai",ps:"叹",vi:"ôi, than thở",ex:"唉，真麻烦 / 唉呀一声 / 唉，算了"},
{h:"哎",p:"āi",hv:"ai",ps:"叹",vi:"ê, này…",ex:"哎，你好 / 哎，等等 / 哎？怎么了"},
{h:"爱护",p:"àihù",hv:"ái hộ",ps:"动",vi:"yêu quý, bảo vệ",ex:"爱护环境 / 爱护动物 / 爱护身体"},
{h:"哎呀",p:"āiyā",hv:"ai nha",ps:"叹",vi:"ôi trời, ôi chao",ex:"哎呀，忘了 / 哎呀，好疼 / 哎呀，太好了"},
{h:"暗",p:"àn",hv:"ám",ps:"形",vi:"tối, âm u",ex:"房间很暗 / 暗色衣服 / 天快暗了"},
{h:"安",p:"ān",hv:"an",ps:"形/动",vi:"yên, an toàn; lắp/đặt (ít gặp)",ex:"平安 / 安静 / 安心"},
{h:"安全带",p:"ānquándài",hv:"an toàn đới",ps:"名",vi:"dây an toàn",ex:"系安全带 / 安全带扣 / 解开安全带"},
{h:"安慰",p:"ānwèi",hv:"an ủi",ps:"动/形",vi:"an ủi; lời an ủi",ex:"安慰朋友 / 受到安慰 / 安慰的话"},
{h:"安装",p:"ānzhuāng",hv:"an trang",ps:"动",vi:"lắp đặt",ex:"安装软件 / 安装空调 / 安装设备"},
{h:"熬夜",p:"áoyè",hv:"ngao dạ",ps:"动",vi:"thức khuya",ex:"经常熬夜 / 熬夜学习 / 熬夜加班"},
{h:"白",p:"bái",hv:"bạch",ps:"形/副",vi:"trắng; uổng, vô ích",ex:"白色 / 白跑一趟 / 白白浪费"},
{h:"傍晚",p:"bàngwǎn",hv:"bàng vãn",ps:"名",vi:"chiều tối",ex:"今天傍晚 / 傍晚时分 / 傍晚回家"},
{h:"半夜",p:"bànyè",hv:"bán dạ",ps:"名/数量",vi:"nửa đêm",ex:"半夜醒来 / 半夜三更 / 半夜出门"},
{h:"薄",p:"báo",hv:"bạc",ps:"形",vi:"mỏng",ex:"薄衣服 / 纸很薄 / 薄薄一层"},
{h:"宝",p:"bǎo",hv:"bảo",ps:"名",vi:"báu, quý",ex:"国宝 / 宝贝 / 宝物"},
{h:"保",p:"bǎo",hv:"bảo",ps:"动/名",vi:"bảo vệ; giữ; bảo đảm",ex:"保密 / 保持 / 保障"},
{h:"保安",p:"bǎo’ān",hv:"bảo an",ps:"名/动",vi:"bảo vệ, an ninh",ex:"小区保安 / 当保安 / 保安人员"},
{h:"宝贝",p:"bǎobèi",hv:"bảo bối",ps:"名",vi:"báu vật; (gọi thân mật)",ex:"我的宝贝 / 宝贝女儿 / 宝贝儿"},
{h:"保持",p:"bǎochí",hv:"bảo trì",ps:"动",vi:"duy trì, giữ vững",ex:"保持安静 / 保持距离 / 保持联系"},
{h:"保存",p:"bǎocún",hv:"bảo tồn",ps:"动",vi:"lưu giữ, bảo quản",ex:"保存文件 / 保存照片 / 保存实力"},
{h:"报到",p:"bàodào",hv:"báo đáo",ps:"动",vi:"đến trình diện",ex:"新生报到 / 按时报到 / 报到处"},
{h:"报道",p:"bàodào",hv:"báo đạo",ps:"动/名",vi:"đưa tin; bản tin",ex:"新闻报道 / 媒体报道 / 现场报道"},
{h:"报告",p:"bàogào",hv:"báo cáo",ps:"动/名",vi:"báo cáo",ex:"写报告 / 工作报告 / 听报告"},
{h:"宝贵",p:"bǎoguì",hv:"bảo quý",ps:"形",vi:"quý giá",ex:"宝贵时间 / 宝贵经验 / 宝贵机会"},
{h:"包裹",p:"bāoguǒ",hv:"bao quả",ps:"动/名",vi:"bưu kiện; gói",ex:"寄包裹 / 打开包裹 / 快递包裹"},
{h:"包含",p:"bāohán",hv:"bao hàm",ps:"动",vi:"bao gồm",ex:"包含内容 / 包含费用 / 包含在内"},
{h:"报警",p:"bàojǐng",hv:"báo cảnh",ps:"动",vi:"báo cảnh sát",ex:"立即报警 / 报警电话 / 报警处理"},
{h:"包括",p:"bāokuò",hv:"bao quát",ps:"动",vi:"bao gồm",ex:"包括我 / 包括费用 / 包括在内"},
{h:"保留",p:"bǎoliú",hv:"bảo lưu",ps:"动",vi:"giữ lại",ex:"保留意见 / 保留权利 / 保留原样"},
{h:"保险",p:"bǎoxiǎn",hv:"bảo hiểm",ps:"名/形",vi:"bảo hiểm; an toàn",ex:"买保险 / 医疗保险 / 保险公司"},
{h:"暴雨",p:"bàoyǔ",hv:"bạo vũ",ps:"名",vi:"mưa lớn",ex:"下暴雨 / 暴雨天气 / 暴雨警报"},
{h:"抱怨",p:"bàoyuàn",hv:"bão oán",ps:"动",vi:"phàn nàn",ex:"抱怨工作 / 抱怨天气 / 不再抱怨"},
{h:"保质期",p:"bǎozhìqī",hv:"bảo chất kỳ",ps:"名",vi:"hạn sử dụng",ex:"过了保质期 / 查看保质期 / 保质期内"},
{h:"包装",p:"bāozhuāng",hv:"bao trang",ps:"动/名",vi:"đóng gói",ex:"产品包装 / 重新包装 / 包装设计"},
{h:"把握",p:"bǎwò",hv:"bả ác",ps:"动/名",vi:"nắm bắt",ex:"把握机会 / 没有把握 / 把握方向"},
{h:"背",p:"bèi",hv:"bối",ps:"名/动",vi:"lưng; cõng",ex:"后背 / 背孩子 / 背书包"},
{h:"背后",p:"bèihòu",hv:"bối hậu",ps:"名",vi:"phía sau; sau lưng",ex:"背后原因 / 背后支持 / 背后说人"},
{h:"背景",p:"bèijǐng",hv:"bối cảnh",ps:"名",vi:"bối cảnh",ex:"文化背景 / 背景音乐 / 社会背景"},
{h:"被子",p:"bèizi",hv:"bị tử",ps:"名",vi:"chăn",ex:"盖被子 / 厚被子 / 折被子"},
{h:"本",p:"běn",hv:"bản",ps:"副/代",vi:"vốn; bản thân",ex:"本来如此 / 本人同意 / 本不应该"},
{h:"本地",p:"běndì",hv:"bản địa",ps:"名",vi:"địa phương",ex:"本地人 / 本地菜 / 本地市场"},
{h:"本领",p:"běnlǐng",hv:"bản lĩnh",ps:"名",vi:"năng lực",ex:"有本领 / 真本领 / 学本领"},
{h:"本人",p:"běnrén",hv:"bản nhân",ps:"代",vi:"bản thân",ex:"本人签字 / 本人负责 / 本人同意"},
{h:"本质",p:"běnzhì",hv:"bản chất",ps:"名",vi:"bản chất",ex:"问题本质 / 本质区别 / 认识本质"},
{h:"必",p:"bì",hv:"tất",ps:"副",vi:"nhất định",ex:"必须完成 / 必然结果 / 必不可少"},
{h:"便",p:"biàn",hv:"tiện",ps:"副",vi:"liền, tiện",ex:"方便 / 随便 / 便于理解"},
{h:"变动",p:"biàndòng",hv:"biến động",ps:"动",vi:"thay đổi",ex:"情况变动 / 价格变动 / 人事变动"},
{h:"便利",p:"biànlì",hv:"tiện lợi",ps:"形/动",vi:"tiện lợi",ex:"生活便利 / 交通便利 / 提供便利"},
{h:"便利店",p:"biànlìdiàn",hv:"tiện lợi điếm",ps:"名",vi:"cửa hàng tiện lợi",ex:"去便利店 / 24小时便利店 / 附近便利店"},
{h:"表达",p:"biǎodá",hv:"biểu đạt",ps:"动",vi:"biểu达",ex:"表达意见 / 表达感谢 / 表达清楚"},
{h:"表面",p:"biǎomiàn",hv:"biểu diện",ps:"名",vi:"bề mặt",ex:"表面现象 / 表面处理 / 表面看"}
];

